package com.amar.webs.dao;

import com.amar.webs.model.SecGroup;
import com.amar.webs.model.SecGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int countByExample(SecGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int deleteByExample(SecGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int insert(SecGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int insertSelective(SecGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    List<SecGroup> selectByExample(SecGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    SecGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SecGroup record, @Param("example") SecGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SecGroup record, @Param("example") SecGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecGroup record);
}